// Auto-generated by make — do not edit
let buildVersion = "0.0.7"
let buildCommit = "ac480d7"
let buildBranch = "main"
let buildDate = "2026-04-15 12:43:25 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
