// Auto-generated by make — do not edit
let buildVersion = "1.9.0"
let buildCommit = "18a71b4"
let buildBranch = "main"
let buildDate = "2026-07-01 20:15:43 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
