// Auto-generated by make — do not edit
let buildVersion = "0.0.3"
let buildCommit = "398d08c"
let buildBranch = "main"
let buildDate = "2026-04-03 23:04:40 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
